included:
    - ../Examples/NativeExamples
    - ../Sources
    - ../Tests
line_length: 300
identifier_name:
    allowed_symbols: "_"
    min_length: 1
nesting:
    type_level:
        warning: 5
#opt_in_rules:
#  - force_unwrapping
